### ISSUE TITLE
Where are the initial pdb files?

### ISSUE THREAD

**Issue by EmperorJia** [DeepDriveMD/DeepDriveMD-pipeline#55]
Hello! I'm replicating this project and I've got a question. 
In `DeepDriveMD-pipeline/test/bba/lassen-integration.yaml`, I see `initial_pdb_dir: /p/gpfs1/brace3/data/bba/ddmd_input`, but I didn't find this directory in the project, except for `DeepDriveMD-pipeline/data/bba/system`. 
Are they the same? If not, would you please provide me the initial pbd files? Thanks in advance.

**Comment by braceal** [comment]
Thanks for your interest! The `initial_pdb_dir` config option allows you to input any molecular system. The data in `DeepDriveMD-pipeline/data/bba/system` is an example of how a single structure could be input to initialize DeepDriveMD.

Here is a note about it in our readme: https://github.com/DeepDriveMD/DeepDriveMD-pipeline#note-on-input-data

The `/p/gpfs1/brace3/data/bba/ddmd_input` is a specific path used in one of our tests, to work with your own data, update this path in the config to be an absolute path to your system directory (as shown in the note).

**Comment by EmperorJia** [comment]
Oh, I got it. Thanks for your quik reply!
